import { getServerSession } from 'next-auth';
import './globals.css'
import { Inter } from 'next/font/google'
import { authOptions } from './api/auth/[...nextauth]/route';
import { redirect } from 'next/navigation';
import NextAuthProvider from '@/auth-provider/page';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect('/api/auth/signin?callbackUrl=/')
  }
  return (
    <html lang="en">
    <NextAuthProvider>
      <body className={inter.className}>{children}</body>
      </NextAuthProvider>
    </html>
  )
}
